### ISSUE TITLE
"Manifest Parsing has failed" error when uploading bot to Teams

### ISSUE THREAD

**Issue by simonleray-meyer** [OfficeDev/microsoft-teams-icebreaker-app#106]
Hi,

I've been struggling to get the IceBreaker bot uploaded to my IceBreaker teams.

I have checked my tenancy policy and I "think" I have made all the right changes so that I can upload a custom app.

I have created the manifest as per steps 3 and made these changes to the file:
developer.name
developer.websiteurl
developer.privacyurl
developer.termsofuseurl
BotID
validdomains

I create a zip file, with just the three files (color, manifest and outline)

When I upload it to Teams, I get the error "Manifest parsing has failed".
[
![001](https://user-images.githubusercontent.com/34058791/96751652-5d50e600-13c5-11eb-8f57-bc74c78010ed.png)
](url)

If I try to upload it in Teams, by clicking on Apps - Upload a Custom App - Upload for My company, I get the error "Something went Wrong"

If I try to upload it in Teams, by clicking on Apps - Upload for me or my Teams, I get the Icebreaker screen up.  When I click on Add, I get the error "Manifest parsing has failed".  If I try and select a Teams, I can choose the Team and the channel.  The "Set up a Bot" button is blue and I can press it.  It then just sits there and does nothing

![002](https://user-images.githubusercontent.com/34058791/96751675-6477f400-13c5-11eb-9517-458719065299.png)

If I try to upload it via the Teams Admin screen - Manage Screen, I just get an error saying "We can't upload the app".

thoughts on what I've done wrong?

**Comment by tonyschocolonely** [comment]
You probably have a typo somewhere. Would you mind sharing excluding the real details ?

**Comment by simonleray-meyer** [comment]
Hi,

I found the error was the same as issue #105.  

I used App Studio to check the package and thats I found out that the small icon was the cause of the issue. It was what was causing the application to fail the validation checks. 

I just resized the small icon using MSPaint from the 20x20 pixels it comes with in the package to 32x32 and sorted.

regards

Simon
