### ISSUE TITLE
Modify message content

### ISSUE THREAD

**Issue by franklinis** [OfficeDev/microsoft-teams-icebreaker-app#272]
I have scheduled the app to pair up people every two weeks. However, the message says it's sent every week.

Can you help me to know if I can modify it and how I can modify it ?

![image](https://user-images.githubusercontent.com/105910928/197775978-24d62037-c718-4559-9302-87349380de4d.png)

**Comment by gsv022** [comment]
Hi @issacfranklin1529 ,
Thanks for raising the query. Modification can be done but it needs to be done at the code level. And if done it will be considered as customization.

**Comment by franklinis** [comment]
@gsv022 

can you help me what I need to do / modify and how I can achieve the requirement

**Comment by gsv022** [comment]
Hi @issacfranklin1529 ,
Please follow these steps mentioned below.

- Fork the Icebreaker repository. Create the new branch on top of that.
- Update the  App Service -resource file.
- Push the changes to newly created branch. 
- Go to App service of existing resource group. Disconnect the present repository and connect to the forked repository and branch and check it out.


Thank you
