### ISSUE TITLE
Resuming matches after pause not available if message is deleted

### ISSUE THREAD

**Issue by diver7** [OfficeDev/microsoft-teams-icebreaker-app#276]
If I pause matching in the Bot chat it sends me a message back with a button to resume matching. This works great except we are deleting all chat messages after 30 days. So if I don't go back and resume matching before the 30 days is up the message and the button get deleted and I have no way of resuming matches. 

The only solution to this I have found is to go into the back end database and edit the users record. It looks like the chat message buttons are just sending a message (ie. "Resume matches") to the bot to tell it to pause and resume matches. Unfortunately the Bot does not allow the user to send any messages to the Bot. So the user can't resume matches by themselves.

**Comment by gsv022** [comment]
Hi @diver7 ,
Thanks for raising the query . We will look into this and get back to you with proper response soon.

**Comment by v-royavinash** [comment]
@diver7 Thanks for your feedback, We are closing this issue as the feature has already been added to our backlog. It will be considered for future releases of based on its priority.
