### ISSUE TITLE
Despite "Pause matches" activated user account is proposed to others

### ISSUE THREAD

**Issue by Sem149** [OfficeDev/microsoft-teams-icebreaker-app#279]
Issue Description

1. User activated "Pause matches" and also does not receive notification
2. However this user is still matched to other colleagues and therefore contacted by them

Is there any way how to disable the matching of colleagues with "pause matches" activates?

**Comment by gsv022** [comment]
Hi @Sem149 ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @Sem149 ,
If not done previously, please try this procedure.

1. Go to Azure Portal--> Open the resource groups-->Select the resource group where the app has been deployed-->Select logic app--> Run the trigger. Then in the UI **It's time for a match!** template should appear. Below is the reference. 
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98143492/215503507-1f1f44bd-eed6-49ad-a363-c9e21921fca1.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/98143492/215505551-6439286a-8a3f-4799-b655-9851429fd626.png">


2. Pause all matches

<img width="545" alt="image" src="https://user-images.githubusercontent.com/98143492/215503743-73a2e2be-d00d-4ad5-90e0-679495ff9b01.png">

3. Once after pausing. Below is the response is expected from the bot.  **Your response was sent to the app** should be coming up.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/98143492/215504624-95d958bb-7610-452e-8244-d8e7cc19f2d4.png">

4. Repeat the first step again.  Now you should not be getting the **It's time for a match!** template.  If this scenario works, **pause matches** is working fine.

Please let us know how it goes.

**Comment by Sem149** [comment]
Internal

Dear @gsv022 

Unfortunately it does not help as he receives an error message when trying to resume his matches:
![image](https://user-images.githubusercontent.com/122532199/217000911-83108f11-402a-4da3-bd43-7835d83d28e6.png)

Do you know what we could do?

Thanks a lot and best regards,
Sebastian

**Comment by Sem149** [comment]
@gsv022 - did you have any chance to view and analyse our error message?

**Comment by gsv022** [comment]
@Sem149 , Could you please share the app service logs. Here is the reference.
<img width="797" alt="image" src="https://user-images.githubusercontent.com/98143492/221926386-6d1cfa79-2ae2-4f1a-acc5-8d56e9819058.png">

**Comment by Sem149** [comment]
Internal

@Sai ***@***.***> we are not able to retrieve this. Only the following is available:
***@***.***

From: Sai Venkat ***@***.***>
Sent: Dienstag, 28. Februar 2023 18:10
To: OfficeDev/microsoft-teams-apps-icebreaker ***@***.***>
Cc: Mueller, Sebastian (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-icebreaker] Despite "Pause matches" activated user account is proposed to others (Issue #279)


@Sem149<https://github.com/Sem149> , Could you please share the app service logs. Here is the reference.
[Image removed by sender. image]<https://user-images.githubusercontent.com/98143492/221926386-6d1cfa79-2ae2-4f1a-acc5-8d56e9819058.png>

**Comment by gsv022** [comment]
As the message is in encrypted state, not able to view the content. Please send the response here directly.

**Comment by Sem149** [comment]
[@Sai Venkat](mailto:notifications@github.com) we are not able to retrieve this. Only the following is available:
![image](https://user-images.githubusercontent.com/122532199/223069106-1a1df9ad-dafc-4705-9fad-70b9bbe9e178.png)

**Comment by Sem149** [comment]
Internal

@Sai ***@***.***> it’s now also included in GitHub directly

From: Sai Venkat ***@***.***>
Sent: Samstag, 4. März 2023 13:08
To: OfficeDev/microsoft-teams-apps-icebreaker ***@***.***>
Cc: Mueller, Sebastian (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-icebreaker] Despite "Pause matches" activated user account is proposed to others (Issue #279)


As the message is in encrypted state, not able to view the content. Please send the response here directly.

**Comment by gsv022** [comment]
> @Sem149 , Could you please share the app service logs. Here is the reference. <img alt="image" width="797" src="https://user-images.githubusercontent.com/98143492/221926386-6d1cfa79-2ae2-4f1a-acc5-8d56e9819058.png">

@Sem149 , Please follow the below steps.

- Go to Azure Portal
- Open the Resource group where Icebreaker has been deployed
- Click on App service(web app)
- Select Deployment center under deployment section
- Go to logs section
- Click on commit id
- Copy the deployment logs and paste it in some text file and share it

**Comment by Sem149** [comment]
Hi @gsv022 

please find the log
[Deployment-Microsoft.Template-20220427182831 (2).zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/10931463/Deployment-Microsoft.Template-20220427182831.2.zip)
[Deployment-Failure-Anomalies-Alert-Rule-Deployment-46dc8364.zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/10931465/Deployment-Failure-Anomalies-Alert-Rule-Deployment-46dc8364.zip)
s

**Comment by gsv022** [comment]
Thanks for sharing the details. We will go through the above files and will get back to you.

**Comment by gsv022** [comment]
@Sem149 , Could you please share the outlook id so that we can discuss the issue internally.

**Comment by Sem149** [comment]
Internal

@Sai ***@***.***> What’s the Outlook ID please?

From: Sai Venkat ***@***.***>
Sent: Donnerstag, 16. März 2023 11:48
To: OfficeDev/microsoft-teams-apps-icebreaker ***@***.***>
Cc: Mueller, Sebastian (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-icebreaker] Despite "Pause matches" activated user account is proposed to others (Issue #279)


@Sem149<https://github.com/Sem149> , Could you please share the outlook id so that we can discuss the issue internally.

**Comment by gsv022** [comment]
@Sem149 , Could you please mail id so that we can discuss the issue internally.

**Comment by Sem149** [comment]
Internal

@Sai ***@***.***> I ask you to please be a little more specific with what you need – whose mail ID do you need or what ID exactly? Thank you!

From: Sai Venkat ***@***.***>
Sent: Freitag, 17. März 2023 12:03
To: OfficeDev/microsoft-teams-apps-icebreaker ***@***.***>
Cc: Mueller, Sebastian (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-icebreaker] Despite "Pause matches" activated user account is proposed to others (Issue #279)


@Sem149<https://github.com/Sem149> , Could you please mail id so that we can discuss the issue internally.

**Comment by v-jaygupta** [comment]
@Sem149 - Can you please share your e-mail Id (preferably Microsoft Teams E-mail Id) so that we can discuss the issue over call.

**Comment by Sem149** [comment]
Internal

@Sai ***@***.***> @***@***.***> that would be ***@***.******@***.***> – problem is that I cannot reproduce the issue but two users are facing the problem that they are not able to resume the IceBreaker bot. Do you have any FAQs or any help that you could provide? What did you find out reading through our logs?

From: v-jaygupta ***@***.***>
Sent: Montag, 20. März 2023 07:56
To: OfficeDev/microsoft-teams-apps-icebreaker ***@***.***>
Cc: Mueller, Sebastian (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-icebreaker] Despite "Pause matches" activated user account is proposed to others (Issue #279)


@Sem149<https://github.com/Sem149> - Can you please share your e-mail Id (probably Microsoft Teams E-mail Id) so that we can discuss the issue over call.

**Comment by gsv022** [comment]
Please provide the email-id so that  we can discuss the issue internally

**Comment by Sem149** [comment]
Internal

@Sai ***@***.***> Sorry - but I don't have the feeling we are getting anywhere here :-(

I have to be honest that I really do not understand the way forward and how you want to support. I have shared our logs, my mail ID but nothing happened.

Please let me know the next steps as we are already going in circles since many weeks without any findings.

Please also let me know if you cannot support, at least then we know.

Thank you and best regards,
Sebastian

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: Sai Venkat ***@***.***>
Sent: Thursday, March 23, 2023 10:51:33 AM
To: OfficeDev/microsoft-teams-apps-icebreaker ***@***.***>
Cc: Mueller, Sebastian (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-icebreaker] Despite "Pause matches" activated user account is proposed to others (Issue #279)


Please provide the email-id so that we can discuss the issue internally

**Comment by v-royavinash** [comment]
@Sem149  We understand that you are feeling stuck with the current situation. To better understand the issue, we would need to connect with you over a call. The email ID you shared above is getting encrypted because you are replying to GitHub via email, which makes it difficult for us to see the ID. The logs you shared don't provide much information about the issue. It would be helpful if you could share the email ID without encryption or take a screenshot of the email ID to avoid encryption.

We appreciate your patience and cooperation throughout this process.

![image](https://user-images.githubusercontent.com/94480537/228089699-c9051162-146c-45f3-b688-eeaec200e2e0.png)

**Comment by gsv022** [comment]
@Sem149 , Could you please let us know the status

**Comment by Sem149** [comment]
Dear both @v-royavinash @gsv022 @v-jaygupta , my mail ID is sebastian.m.mueller@allianz.de.
But before scheduling a meeting please at least give me at least a few findings. We have 2 1/2 months of going back and forth and not even one idea of what could cause the issue :-(

As I am not the affected user I will not be able to give you lot of insights.

**Comment by gsv022** [comment]
Thanks for the update, We are closing out the issue. Please log a new issue if any issue faced with respect to Icebreaker. We are happy to assist you.
 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/98143492/229776882-e3f00aec-3564-4bfc-b0ec-1507bca51e92.png">
