### ISSUE TITLE
Bot showing as disabled

### ISSUE THREAD

**Issue by BDE-95** [OfficeDev/microsoft-teams-icebreaker-app#282]
We run the bot every month, and in January, we received reports of the bot showing as disabled. 
![CoffeeForTwo_BotDisabled](https://user-images.githubusercontent.com/105078642/216412240-d0fe8c17-e271-4461-af07-a09c64ae2548.png)

Attaching the message our end users are seeing. The application is still allowed/in Teams Admin Center, and I don't see any configurations or messages on the resources in Azure that would cause the bot to be disabled. Is there a way to tell or places to look to see where/how the bot is disabled?

**Comment by gsv022** [comment]
Hi @BDE-95 ,
Thanks for raising the query. 

- Please send us the screenshot of whether the application is marked as allowed in teams admin center for the one who installed Icebreaker to the teams. Below is the screenshot for reference. 

<img width="468" alt="image" src="https://user-images.githubusercontent.com/98143492/216530821-842a7136-a4ca-4bd7-ab97-b3ef1428204f.png">

- If there is any custom policy for the application, user must subscribe to the same policy.

**Comment by BDE-95** [comment]
Hello,
Here is a screenshot of our App Permission Policy
![image](https://user-images.githubusercontent.com/105078642/216604185-34ed299b-f9ff-404e-82b7-7cff4f248e5e.png)

The "Coffee For Two" is the Icebreaker bot. 
And here is a screenshot of the App, which is showing as Allowed
![image](https://user-images.githubusercontent.com/105078642/216604318-33c45602-7cfb-42e2-8f7d-ead1f93f9dd3.png)

**Comment by gsv022** [comment]
@BDE-95 , Does the issue still continues?

**Comment by BDE-95** [comment]
Hi there. Apologies for my delay.
The issue still continues, yes
