### ISSUE TITLE
Two matches at once

### ISSUE THREAD

**Issue by enriqueqs** [OfficeDev/microsoft-teams-icebreaker-app#286]
Someone in my organisation has been matched with two different people at the same time. It has happened twice for this person. Any ideas on how to fix it?

**Comment by gsv022** [comment]
Hi @enriqueqs ,
Thanks for raising the query. Could you please share the supporting screenshot of the issue.

**Comment by enriqueqs** [comment]
> Hi @enriqueqs ,
> Thanks for raising the query. Could you please share the supporting screenshot of the issue.
here is the screenshot @gsv022 :)
![MicrosoftTeams-image2](https://user-images.githubusercontent.com/55209162/224038895-354334b2-0b8f-4a1e-9966-20759ceae8a1.png)

**Comment by enriqueqs** [comment]
@gsv022 just to further this. Now another person in my organisation contacted with the same issue, 3rd time that this new person gets matched twice in a day. Let me know if you have any fixes or suggestions

**Comment by gsv022** [comment]
Thanks for sharing the details. We are checking on this issue and will get back to you with proper response soon.

**Comment by gsv022** [comment]
Could you please share the outlook id( or MS Teams Id) so that we can discuss the issue internally.

**Comment by enriqueqs** [comment]
@gsv022 my email is enrique.salazar@danfoss.com

**Comment by enriqueqs** [comment]
Hello, can we reopen this? and what does outlook id mean? @gsv022
