### ISSUE TITLE
Icebreaker - Two instance but points to different Azure subscription

### ISSUE THREAD

**Issue by vzantua** [OfficeDev/microsoft-teams-icebreaker-app#290]
Is that recommended or will cause an issue?
Our setup:
- Deployed 2 instances but points to different Azure subscription
- Two different app name deployed in MS Teams
-

**Comment by v-jaygupta** [comment]
Hi @vzantua ,
This shouldn't be an issue unless both the instances are added to 2 different teams

**Comment by vzantua** [comment]
Team 1, added the 1st app version
For 1st deployment, pairing happens for the last four Mondays
Team 2, added the 2nd app version
After 2nd deployment last week, no pairing happened yesterday Monday.
Thoughts? What/Where to check?
Thanks!

**Comment by gsv022** [comment]
@vzantua , Please respond to the below queries.

- It is clear that two instances are from different subscriptions but please clarify whether the instances are added to the same team or different team? 
- To check the functionality is working fine or not. Here is the reference.
-  Could you please trigger the logic app to check whether a message template is appearing or not in the teams. 
<img width="949" alt="image" src="https://user-images.githubusercontent.com/98143492/188873700-a2bae871-88d5-4ea6-b6c5-3eb51a6b2971.png">

**Comment by vzantua** [comment]
It is clear that two instances are from different subscriptions but please clarify whether the instances are added to the same team or different team? 
-> 1st instance was added to 1st Team a month ago and 2nd was a week ago to a fresh new Team

To check the functionality is working fine or not. Here is the reference.
Could you please trigger the logic app to check whether a message template is appearing or not in the teams.
-> Is the message template the intro message in Teams? I triggered it already 3 days ago and below is the recent status. The last 3 sessions Succeeded.
Status                 Start Time                                 Identifier                                       Duration
Succeeded    3/20/2023, 2:00 PM    08585222644312422575405645686CU17   275 Milliseconds

**Comment by gsv022** [comment]
@vzantua , Once you trigger the logic app, Are you able to get a message template saying that "Its time for a match" in the teams.

**Comment by vzantua** [comment]
Nothing. I deleted the 1st instance app in Teams admin Center but still shows up in the Team that I've added it. Do I just wait for it to be removed or I need to delete from there?

**Comment by gsv022** [comment]
Yes, it takes atleast 24hrs for the application to get erased from teams. Please keep us posted.

**Comment by vzantua** [comment]
I tried adding the app in a Team today and not even getting the welcome message. Thoughts?

**Comment by gsv022** [comment]
@vzantua , Have you tried adding the app to any particular team or just added it to the tenant. Please confirm

**Comment by vzantua** [comment]
Added to the tenant. All working now after I removed the 1st instance components (Azure, Reg App, etc.) and leave the 2nd instance only.

**Comment by gsv022** [comment]
@vzantua ,Thanks for the update. Please let us know if you have any queries related to Icebreaker. If no, we are good to close out the issue.

**Comment by vzantua** [comment]
You can close it now. Thanks!
