### ISSUE TITLE
deploy.ps1 error

### ISSUE THREAD

**Issue by Hennericho** [OfficeDev/microsoft-teams-icebreaker-app#291]
Hi all, 
There is an issue in the deply.ps1 file. It is using outdated and unsupported parameters when creating the app.
On line number 204 & 217 there is a command:
`az ad app create --display-name $appName --available-to-other-tenants $MultiTenant --oauth2-allow-implicit-flow $AllowImplicitFlow`

This needs to be be changed to:
`az ad app create --display-name $appName --sign-in-audience AzureADMultipleOrgs`

**Comment by gsv022** [comment]
Hi @Hennericho ,
 Thanks for the suggestion. We will look into the inputs suggested and verify it from our end. Then will do the necessary

**Comment by v-royavinash** [comment]
@Hennericho To avoid errors during deployment, we recommend using Azure CLI version 2.30.0. In future releases, we will address the highlighted issue and provide support for the latest Azure CLI version, which in turn utilizes the latest parameters.
