### ISSUE TITLE
Manifest.json bug

### ISSUE THREAD

**Issue by Hennericho** [OfficeDev/microsoft-teams-icebreaker-app#292]
Hi all,

There is a bug in the generated app manifest.json file. There is an object "localizationInfo" with a child array object "additionalLanguages". The file paths of each additional language don't resolve when trying to upload the manifest to the Teams App store.

**Comment by gsv022** [comment]
Hi @Hennericho ,
Thanks for raising the query. There was a issue related to localization previously  but it got fixed recently. Please take the latest code and fill the values in the manifest file  then upload it. It will work as expected.
