### ISSUE TITLE
We deployed this solution which has been working great for last 14 months however since last 2 runs, pairings are not happening 

### ISSUE THREAD

**Issue by ara4277** [OfficeDev/microsoft-teams-icebreaker-app#293]
we need some tips to resolve pairing not happening issue, when backend logic app services jobs its sending paired created for January 2023 and from that time backend cosmos DB is not updated. We need help to resolve this PRODUCTION issue, its been show-stopper, for some reason ICE BREAKER WATER COOLER APP Is not able to sync the members part of the MS TEAMS channel it is associated, display possible pairings info upfront. Please help us to resolve this PROD issue & inline to escalate via MS Support but want contributor's attention here.

**Comment by gsv022** [comment]
Hi @ara4277 ,
Thanks for raising the query. We have recently released a fix for localization issue. 

- Please take the code from latest
- Configure the manifest with the same parameters
- While zipping include all the language files.
- Re-upload it.


Keep us posted.

**Comment by ara4277** [comment]
Thanks for your response
