### ISSUE TITLE
Logic App throws authentication issue

### ISSUE THREAD

**Issue by sanojgopinath04** [OfficeDev/microsoft-teams-icebreaker-app#295]
our icebreaker app logic was functioning till January, but started throwing error from last two months . 
Below is the error we get in our icebreaker logic app

"message": "An error has occurred.",
"exceptionMessage": "Response status code does not indicate success:401(untheorized)",
"exceptionType": "System.Net.Http.HttpRequestException",",
"stackTrace": " at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefereshTokenAsync>d__34.MoveNext().

Can someone help.

**Comment by gsv022** [comment]
Hi @sanojgopinath04 ,
Thanks for raising the query. There is a chance that secret might have expired. If yes, please update the secret.
