### ISSUE TITLE
icebreaker-How do I see who has been paired with who in Azure AD Application Insights

### ISSUE THREAD

**Issue by cgjeb** [OfficeDev/microsoft-teams-icebreaker-app#297]
Hi,

I'm having an issue where a user is not receiving the pairing, yet he is in the Teams group/channel that has Icebreaker deployed.

Can you please share the link to the exact event section in Applications Insight described here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/92. It is something to do with the custom event called ''ProcessedPairups"? I can't seem to find it in Azure AD.

Thank you.

**Comment by gsv022** [comment]
Hi @cgjeb ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by v-royavinash** [comment]
@cgjeb As we are only logging users' channel account IDs and not their details, it is not possible to retrieve the exact pairing members from Application Insights. We have already added backlog item to  regarding reporting to give you the user details which we will be working on future releases. However, to view the summary please refer the custom events to get details of,

- Installed Teams Count
- Pairs Notified Count
- Users Notified Count

![image](https://user-images.githubusercontent.com/94480537/235011455-1ca1e633-7c53-4b56-95fd-64bad221eaa4.png)


![image](https://user-images.githubusercontent.com/94480537/235011486-470cf98c-09bf-4ee4-99a0-48ebd778221d.png)

**Comment by cgjeb** [comment]
@v-royavinash @gsv022  Thank you for the update.
However, I've tried to go into Application Insights and events and need help finding a way to see the proccessedpairups.

![image](https://user-images.githubusercontent.com/45824267/236420907-123c3bcf-9e37-40e9-851e-fae56b93f640.png)


Please send me a detailed guide, as a document, with all the steps.

Regards,
Edwin
