### ISSUE TITLE
Matched with same person 3x in 5weeks

### ISSUE THREAD

**Issue by vzantua** [OfficeDev/microsoft-teams-icebreaker-app#299]
With Team members around 50, can Icebreaker identify that the person was matched this week then it should find a new match next week or the succeeding weeks? Can we control this logic? Thanks!

**Comment by v-royavinash** [comment]
The matching process in Icebreaker is performed using a random algorithm that cannot be manually controlled. The overall purpose of Icebreaker is to match pairs that are not predetermined. As there are 50 members in the channel, the likelihood of getting the same matching pair is very minimal.

**Comment by vzantua** [comment]
But 3x with the same person in 5weeks? The algorithm should be reviewed I think.

**Comment by vzantua** [comment]
bot, my post which is a question and didn't get an answer. Update your logic please.

**Comment by vzantua** [comment]
> The matching process in Icebreaker is performed using a random algorithm that cannot be manually controlled. The overall purpose of Icebreaker is to match pairs that are not predetermined. As there are 50 members in the channel, the likelihood of getting the same matching pair is very minimal.

3x with the same person in 5weeks? The algorithm should be reviewed I think. Feedback?
