### ISSUE TITLE
Icebreaker App Architecture Questions

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-icebreaker-app#302]
Hi

I looked into deploying Icebreaker at EY several years ago and encountered the following issues.
1.	Scaling Issue- the option to opt out of virtual pairings requires database storage and with the current architecture will not scale to a large organisation
2.	Matching Issue- if you are a member of multiple teams who have IceBreaker installed, you can only be matched by one team and it is not possible to know which team the pairing originated.
3.      Is it possible to control the use of Icebreaker using a security group?

I now have re-newed interest to deploy this app and would like to know if the architecture remains unchanged and we can still expect scaling issues and also if the multiple team issue is resolved as I believe you were planning to implement a fix for this in a version release.

**Comment by gsv022** [comment]
Hi @EYSue ,
Thanks for raising the query. Please give us sometime and will get back to you with proper response soon.

**Comment by gsv022** [comment]
@EYSue ,

- __Scaling Issue- the option to opt out of virtual pairings requires database storage and with the current architecture will not scale to a large organisation_, Could you please provide information on the user base that your particular team is targeting? What are the specific concerns you have regarding the scaling aspect?
- For more info on the pair ups- 
Go to App insights-->Events--> Choose **during** like 24 hours/last 60 days as per your requirement-->Sroll to the bottom in the same page-->Under Event statistics, **ProcessedPairUps**, **Usersactivity** etc.,-->Here we can more info.
Here is one of the references
<img width="917" alt="image" src="https://user-images.githubusercontent.com/98143492/236487349-767df5b3-6fcf-45fb-bc05-37fc829968d3.png">

-  _Is it possible to control the use of Icebreaker using a security group?_, Could you please provide what's the use case of security group in your Icebreaker bot.

**Comment by EYSue** [comment]
Thanks Sai, I am meeting with the developer team tomorrow and then I will provide more context.

**Comment by EYSue** [comment]
Sai, these are the specific questions 
1. What’s the rationale behind choosing Cosmos DB for data persistence?
2. Can we use a low-cost alternative like Azure SQL for persistence layer? If yes, will there be any implications on scale?
3. Our plan is to scale this solution for around 400K employees across the globe and we expect pairings (across different Teams teams) to happen in volumes of hundreds of thousands every month – will the existing design cater to these requirements by just scaling up/out or will it require a complete redesign?

**Comment by gsv022** [comment]
@EYSue , We noted your points and will discuss with the team internally. We will keep you posted.

**Comment by v-royavinash** [comment]
@EYSue We have responded to the queries on app architecture internally over mail. Please let us know if any further assistance is required.
