### ISSUE TITLE
Application Insights-view proccessedpairups-Ref.#297

### ISSUE THREAD

**Issue by cgjeb** [OfficeDev/microsoft-teams-icebreaker-app#303]
Can you please re-open?
 https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/297?

That was my original question.
-----------------
I'm having an issue where a user is not receiving the pairing, yet he is in the Teams group/channel that has Icebreaker deployed.

Please share the link to the exact event section in Applications Insight described here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/92. Is it something to do with the custom event called ''ProcessedPairups"? I can't seem to find it in Azure AD.
-----------------------------------
Thank you.

**Comment by gsv022** [comment]
Hi @cgjeb ,
Thanks for raising the query. Here is the procedure.

- Go to App insights-->Events--> Choose **during** like 24 hours/last 60 days as per your requirement-->Sroll to the bottom in the same page-->Under Event statistics, **ProcessedPairUps** can be found-->Click on the ProcessedPairUps -->You can have view as you referred  #92
<img width="917" alt="image" src="https://user-images.githubusercontent.com/98143492/236487349-767df5b3-6fcf-45fb-bc05-37fc829968d3.png">

- Please share the screenshot of the processed pairups it will be helpful for better troubleshooting

**Comment by cgjeb** [comment]
@gsv022  Thank you very much.

I found the option.

![image](https://user-images.githubusercontent.com/45824267/236509853-5f73be74-87fe-4f1b-9864-e933435ccfa4.png)

**Comment by gsv022** [comment]
Please let me if you need anything otherwise we can make it to closure

**Comment by cgjeb** [comment]
@gsv022 Please close this. 
Thank you for your help.
