### ISSUE TITLE
Ice-breaker apps-Failure Anomalies reported

### ISSUE THREAD

**Issue by cgjeb** [OfficeDev/microsoft-teams-icebreaker-app#304]
Hi support,

Can you please assist us In troubleshooting multiple failures wih all our deployed icebreaker apps?
Is it something that you have changed in the backend?

I have attached r
![failed icebreaker](https://user-images.githubusercontent.com/45824267/236425844-3d055d09-3386-4d7f-8d0f-130091a4268f.JPG)
elated screenshots.
![failed 2](https://user-images.githubusercontent.com/45824267/236425885-829eecaa-67fe-44b2-bd13-1fdbd930c679.JPG)
![status code 500](https://user-images.githubusercontent.com/45824267/236425915-3798f8e7-d011-4cd3-8d81-acafe35c65ff.JPG)
[status code 500.txt](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/11405055/status.code.500.txt)

Thank you.

**Comment by gsv022** [comment]
Hi @cgjeb ,
Thanks for sharing the logs at the earliest. We will check this at our end and will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @cgjeb ,
Please share your outlook id. We can discuss the issue internally

**Comment by cgjeb** [comment]
Hi @v-royavinash  and @gsv022  how can I share my Outlook or work email privately with you and not as a comment here? I don't see the option to directly inbox.

Thank you.

**Comment by gsv022** [comment]
Please share your outlook id in a text file and once I acknowledge it you can revert the comment. This way works right!

**Comment by cgjeb** [comment]
@gsv022 
Please acknowledge.

**Comment by gsv022** [comment]
Received the outlook id thank you

**Comment by cgjeb** [comment]
> Acknowledged

Thank you.

**Comment by gsv022** [comment]
As we had a call, we recommended some implementations. If you are still facing any issue please log a new issue we are happy to assist you.
