### ISSUE TITLE
Icebreaker: "This card action is disabled because you've blocked."

### ISSUE THREAD

**Issue by jeiler1** [OfficeDev/microsoft-teams-icebreaker-app#305]
Greetings,

I have a customer who is getting the following error with his new laptop.

![Icebreaker--error](https://user-images.githubusercontent.com/131718560/236641888-a4077fbc-30da-4aef-8dae-be927913d202.png)

Customer can access Icebreaker on his old laptop and on his phone, but not on his new laptop.

**Comment by gsv022** [comment]
Hi @jeiler1 ,
Thanks for raising the query.  The same kind of issue already opened i.e., #298 . Please follow up in the same issue. This can considered as duplicate.
