### ISSUE TITLE
ICEBREAKER: Can't update Subscription or create new Resource Group

### ISSUE THREAD

**Issue by melindahervey** [OfficeDev/microsoft-teams-icebreaker-app#42]
Hello there! I can't change the Subscription or create a new Resource Group (Step 2 of deployment guide). When I click the drop down arrow under Resource Group there are no available groups.

**Comment by nishandi** [comment]
Hi @melindahervey , are you able to create resource groups otherwise in your Azure subscription? Do you have access to any current resource group in your organization?

**Comment by melindahervey** [comment]
I’m not sure. I haven’t had the need to use Azure prior to this so my guess is no. What do I need to do as my team would like to start using Icebreaker and I need to get past that step to make it happen.

**Comment by nishandi** [comment]
Hi @melindahervey, It appears to me that there may be access limitations in your Azure subscription. Have you tried reaching out to your central IT peers? I'd love to also explore other ways you can get the bot for your team... can you please send me a note at nidhi.shandilya AT microsoft.com?

**Comment by melindahervey** [comment]
I’m not sure what you mean by Central IT peers. Our help desk? Yes, that’s where I started and they recommended that I contact the general help desk. Just sent you an email at the below address.
