### ISSUE TITLE
Opt out?

### ISSUE THREAD

**Issue by allywilson1** [OfficeDev/microsoft-teams-icebreaker-app#58]
Is there any way to opt out for individuals once this service has been deployed?

**Comment by coderkrishna** [comment]
Post deployment, here are the actions: 
1. The Icebreaker bot manifest is to be created
2. The necessary team is to be created in the Teams UI
3. The Icebreaker bot manifest is then to be added into the newly created team in Step 2.
4. Then you would add individuals into the team that is created in Step 2. 
5. As each person gets added, the bot will send a welcome message in a personal scope, and from there the individual can opt out

**Comment by allywilson1** [comment]
I understand, but I feel it misses out on the people who are added to entire teams, involuntarily.

**Comment by coderkrishna** [comment]
There are some tips listed here as best practices: 
https://github.com/OfficeDev/microsoft-teams-icebreaker-app/wiki/Best-practices-when-using-Icebreaker

**Comment by allywilson1** [comment]
The BP for this is the app deployer, not the end user.

Imagine you are a member of a Teams, and Icebreaker is deployed. You now have to on a daily, weekly, whatever, be teamed up with someone else who you may or may not know, who may or may not, give a hoot who you are. 

It's invasive, and the only way out is to be rude or "not a team player."

**Comment by coderkrishna** [comment]
You have the ability to pause matches. You can pause in the following manner:
1. Let's say that you are added to a team, and you would get a message from the bot like this: 
![image](https://user-images.githubusercontent.com/5623947/77475707-72857800-6dd6-11ea-8b7c-6c397defeda9.png)
(I have marked up the image to cover people's names, and also for showing an example here). If you don't want to be matched with anyone.... You can click "Pause all matches" this way when the first round of pairings come in, you won't be matched. You don't have to specifically wait to be matched with someone to opt out

**Comment by allywilson1** [comment]
I was not aware of that feature. Thank you.

**Comment by coderkrishna** [comment]
Hopefully that answers, your question, and I can close this issue?
