### ISSUE TITLE
Deployment failes on Cosmos DB Account

### ISSUE THREAD

**Issue by molislaegers** [OfficeDev/microsoft-teams-icebreaker-app#59]
Last two days I've tried to deploy the Icebreaker app. 

I keep getting this error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"ServiceUnavailable\",\r\n \"message\": \"Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.\\r\\nActivityId: c49ceab9-6fed-4c11-a884-5b99d1c073a9, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, 

etc etc.

It doesn't matter what region I choose. Is anyone able to deploy this app? Is it something in my subscription?

**Comment by mstam13** [comment]
Hi, I receive the same error, tried different regions, different subscriptions. I've tried several times last week and today again, same error.

**Comment by Jag-SB** [comment]
Hi,

Same here, been trying all week, including the weekends to see if the servers are quiet and same issue

**Comment by kthurman** [comment]
Same error here.  Is this a DB permission error on our side or theirs or something else?

**Comment by ritikchanna** [comment]
Are you using free subscription ?

**Comment by molislaegers** [comment]
I'm using 'Pay-as-you-go'

**Comment by ritikchanna** [comment]
I was getting this same error when I was deploying at SouthEast Asia with free subscription. 
I was able to deploy using paid subscription.

**Comment by JaggB** [comment]
We're also on paid subscription, does this have anything to do with azure permissions and accounts?

**Comment by mstam13** [comment]
I've figured it out, you have to use one of the 5 US regions, the Cosmos DB can only be created in one these regions.
![image](https://user-images.githubusercontent.com/32320109/79334821-49fa2500-7f21-11ea-9e83-a161877da789.png)

**Comment by JaggB** [comment]
After speaking to  Microsoft Support, it seems like Azure is maxed out. Managed to deploy it to North Europe

**Comment by molislaegers** [comment]
North Europe didn't work for me either and I prefer to deploy within Europe.. I'll try again in a few weeks.

**Comment by molislaegers** [comment]
This issue is resolved
