### ISSUE TITLE
Icebreaker not showing Propose Meetup button

### ISSUE THREAD

**Issue by milochau** [OfficeDev/microsoft-teams-icebreaker-app#64]
We freshly installed icebreaker in our Azure subscription and loaded the app in Teams. A specific Team is created where Icebreaker as app is included. New users to the team only see the option "Take a tour" and "Pause all matches".  The button "propose meetup" is unavailable. 

In the logging in Azure I was not able to find any errors which might indicate this behavior. The app in Azure is deployed in an environment where Application Insight is available. 

What should be checked next? 

[Doc1.docx](https://github.com/OfficeDev/microsoft-teams-icebreaker-app/files/4520503/Doc1.docx)

**Comment by coderkrishna92** [comment]
@milochau Okay so for this, you would need to let the pairups happen between users for them to see the Propose Meetup button

**Comment by milochau** [comment]
@coderkrishna92 ; no worries. I also didn't update the issue. Indeed it relates to the logic app schedule, at next trigger an invite will be sent. Or, what I did is to execute the schedule from the Azure portal for a first meetup.

Thanks for the reply!

**Comment by coderkrishna92** [comment]
@milochau Glad to help
