### ISSUE TITLE
After Deployent: The API doesn't work

### ISSUE THREAD

**Issue by molislaegers** [OfficeDev/microsoft-teams-icebreaker-app#66]
I've done a new deployment, but after calling the url of the API, I get the message:

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

URL (example): https://icebreaker-xxxxxxxxxx.azurewebsites.net/api/messages
on https://icebreaker-xxxxxxxxxx.azurewebsites.net/ get this response: 

> Hey, App Service developers!
> 
> Your app service is up and running.
> Time to take the next step and deploy your code.

Redeploying doesn't help.

**Comment by coderkrishna92** [comment]
@molislaegers No need for the redeployment. Just make sure to restart the web app service though on the Azure portal

**Comment by molislaegers** [comment]
@coderkrishna92 Sorry for my late answer (I had a few days off), but restarting doesn't help.

I keek getting "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." on /api/messages

**Comment by coderkrishna92** [comment]
Try this instead: 
1. Navigate to your resource group where the icebreaker resources are deployed.
2. Navigate into the bot web app service
3. Restart the web app service, and wait for a few minutes before navigating to the "/api/messages" endpoint.
4. Navigate to the "/api/messages" endpoint and attach the screenshot here, if anything happens

**Comment by molislaegers** [comment]
Sorry for the late reply: your solution didn't help @coderkrishna92 but I've deleted it all and redeployed. Now I've finally got it working like it should
