### ISSUE TITLE
Icebreaker App

### ISSUE THREAD

**Issue by andyjfsmith** [OfficeDev/microsoft-teams-icebreaker-app#70]
Step 1: Register Microsoft Azure AD application

ii Supported account types: Select "Accounts in any organizational directory"

Why does this need to be "Accounts in any organizational directory"? From a security standpoint, this should be set to "Accounts in this organizational directory only".

Are there any implications if I set the Azure AD app registration to "Accounts in this organizational directory only"?

Please advise.

Thank you!

**Comment by rashmi-dixit** [comment]
Multi tenant configuration is required for bot to work when there is manual app registration i.e. manually create your own app ID (and password).
For more details please refer important section in the below page:-
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0#manual-app-registration
